import eslint from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    ignores: ['build/*', 'notebooks/*', 'eslint.config.mjs', 'vite.config.ts'],
  },
  {
    plugins: {
      import: importPlugin,
    },
    rules: {
      'import/no-default-export': 'error',
      'no-constant-condition': 'warn',
      'no-case-declarations': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'indent': 'off',
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/camelcase': 'off',
      '@typescript-eslint/indent': 'off',
      'linebreak-style': ['warn', 'unix'],
      'semi': ['warn', 'always'],
      'no-cond-assign': ['warn', 'always'],
      'no-trailing-spaces': 'warn',
      'no-debugger': 'warn',
      'arrow-body-style': 'off',
      'template-tag-spacing': ['warn', 'never'],
      'object-curly-spacing': ['warn', 'always'],
      'array-bracket-spacing': ['warn', 'never'],
      'computed-property-spacing': ['warn', 'never'],
      'no-else-return': 'warn',
      'no-floating-decimal': 'warn',
      'no-lonely-if': 'warn',
      'no-unneeded-ternary': 'warn',
      'no-useless-return': 'warn',
      'template-curly-spacing': ['warn', 'never'],
      'object-property-newline': [
        'warn',
        {
          allowAllPropertiesOnSameLine: true,
        },
      ],
      'no-sequences': 'warn',
      'key-spacing': 'warn',
      'no-useless-escape': 'off',
      'keyword-spacing': 'warn',
      'brace-style': 'off',
      'curly': ['warn', 'all'],
      'block-spacing': 'warn',
      'space-before-blocks': 'warn',
      'nonblock-statement-body-position': ['warn', 'below'],
      'dot-location': ['warn', 'property'],
      'function-call-argument-newline': ['warn', 'consistent'],
      'object-curly-newline': [
        'warn',
        {
          ObjectExpression: { multiline: true, consistent: true },
          ObjectPattern: { multiline: true, consistent: true },
          ImportDeclaration: { multiline: true, consistent: true },
          ExportDeclaration: { multiline: true, consistent: true },
        },
      ],
      'import/no-named-as-default-member': 'off',
      'import/order': 'off',
      'import/no-duplicates': 'off',
      'import/no-unresolved': 'off',
      'import/default': 'off',
      'import/no-named-default': 'off',
      'import/no-named-as-default': 'off',
      'import/namespace': 'off',
      'prefer-const': 'warn',
      'no-var': 'warn',
    },
  },
);
