export const BACKEND_NOTION_URL = 'https://www.notion.so/needlist/Backend-API-Guide-2d4bd1695bad80179e0aefa92312d01c';
export const FRONTEND_NOTION_URL = 'https://www.notion.so/needlist/Frontend-Guide-2d4bd1695bad80ca9621d29accce51e4';
export const NEEDS = [
  {
    id: 'NL-2024-001',
    title: 'Winter Coats for Kids',
    org: 'Safe Haven Youth',
    category: 'Clothing',
    quantity: 50,
    urgency: 'Urgent',
    status: 'Active',
    date: 'Oct 24, 2024',
  },
  {
    id: 'NL-2024-002',
    title: 'Canned Food Drive',
    org: 'City Food Bank',
    category: 'Food',
    quantity: 200,
    urgency: 'Normal',
    status: 'Active',
    date: 'Oct 22, 2024',
  },
  {
    id: 'NL-2024-003',
    title: 'Laptops for Learning',
    org: 'Tech for All',
    category: 'Electronics',
    quantity: 15,
    urgency: 'High',
    status: 'Pending',
    date: 'Oct 20, 2024',
  },
  {
    id: 'NL-2024-004',
    title: 'Medical Kits',
    org: 'Global Health Corp',
    category: 'Medical',
    quantity: 100,
    urgency: 'Urgent',
    status: 'Active',
    date: 'Oct 19, 2024',
  },
  {
    id: 'NL-2024-005',
    title: 'School Supplies',
    org: 'Bright Future School',
    category: 'Education',
    quantity: 500,
    urgency: 'Normal',
    status: 'Fulfilled',
    date: 'Oct 15, 2024',
  },
  {
    id: 'NL-2024-006',
    title: 'Hygiene Packs',
    org: 'Community Care',
    category: 'Health',
    quantity: 75,
    urgency: 'Normal',
    status: 'Active',
    date: 'Oct 12, 2024',
  },
  {
    id: 'NL-2024-007',
    title: 'Volunteer Drivers',
    org: 'Senior Wheels',
    category: 'Service',
    quantity: 5,
    urgency: 'High',
    status: 'Active',
    date: 'Oct 10, 2024',
  },
];
